contacts_app/contacts_app/app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'

urlpatterns = [
    url(r'^register/$',views.register,name="register"),
    url(r'^user_login/$',views.user_login,name="user_login"),
]

contacts_app/contacts_app/contacts_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^app/',include('app.urls')),
    url(r'^logout/$',views.user_logout,name="logout"),

]

contacts_app/contacts_app/app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

	user = models.OneToOneField(User)

	contact_number = models.IntegerField(blank=False)

	def __str__(self):
		return self.user.username


class ContactsInfo(models.Model):
	
	name = models.CharField(max_length=128)
	contact_entry=models.IntegerField(blank=True)
	username = models.CharField(max_length=128, blank=False)

	def __str__(self):
		return self.username

contacts_app/contacts_app/app/forms.py
from django import forms
from django.contrib.auth.models import User
from app.models import UserProfileInfo,ContactsInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password',)

class ContactsInfoForm(forms.ModelForm):
	class Meta():
		model =  ContactsInfo
		fields = ('name','contact_entry',)


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('contact_number',)

contacts_app/contacts_app/app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from app.forms import UserForm, UserProfileInfoForm,ContactsInfoForm
from app.models import UserProfileInfo, ContactsInfo

# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

def index(request):  
    contact_form = ContactsInfoForm()	
    user_list = ContactsInfo.objects.filter(username=request.user.username)	 
    if request.method == "POST":
    	contact_form = ContactsInfoForm(data=request.POST)

    	if contact_form.is_valid():
    		cont = contact_form.save()
    		cont.username=request.user.username
    		cont.save()
    		return render(request,'app/index.html',{"contact_form":contact_form,"users":user_list})

    	


    	else:
    		print(contact_form.errors)
    		return render(request,'app/index.html',{"contact_form":contact_form,"users":user_list})


    else:
        		
    	return render(request,'app/index.html',{"contact_form":contact_form,"users":user_list})

def register(request):
	
	registered=False

	if request.method == "POST":

		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			profile.save()

			registered = True
		else:
			print(user_form.errors,profile_form.errors)

	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()

	 
	return render(request,'app/registration.html',{
		               'user_form':user_form,
		               'profile_form':profile_form,
		               'registered':registered}) 

def user_login(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)

				return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse("Your account is not active")

		else:
			print("someone tried to login and failed")
			return render(request,'app/login.html',{})	
	else:

		return render(request,'app/login.html',{})				


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

    

contacts_app/contacts_app/templates/app/base.html
<!DOCTYPE html>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        

  </head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
   <div class ="container">
	<ul class ="nav navbar-nav">
	 <li><a href="{% url 'index' %}" class="navbar-brand">
	   Space</a></li>
	 <li><a href="{% url 'admin:index' %}" class=navbar-link>
	 	Admin</a></li>
	 <li><a href="{% url 'app:register' %}" class=navbar-link>
	 	Register</a></li>

	 	{% if user.is_authenticated %}
	 	 <li><a href="{% url 'logout' %}">Logout</a></li>	  
         {% else %}
         <li><a href="{% url 'app:user_login' %}">Login</a></li> {% endif %}  	

			</ul>

		</div>
		
	</nav>

<div class="container">
	{% block body_block %}
	{% endblock %}
</div>

</body>
</html>

contacts_app/contacts_app/templates/app/index.html
{% extends "app/base.html" %}
{% block body_block %}


 <div class = "jumbotron">
 <h1 align="center" style="font-family:OCR A Std, monospace">Space</h1>
  <h2 align="center" style="font-family:OCR A Std, monospace">For You!</h2>

 {% if user.is_authenticated %}
<!-- id the user is loggen in then display thee
contacts and give the option of adding a new number to the contacts models   -->
 <h2 align="center" style="font-family:OCR A Std, monospace">Welcome {{ user.username }}</h2>
   
<form method="POST">
	{% csrf_token %}
	{{ contact_form.as_p }}
	<input type="submit" name="" value="Add">
	
</form>

<hr>
<!-- Now we will display the list of the contacts -->



 {% if users%}

<div class="row">
       {% for person in users %}
<div class="col-sm-3">
<div class="card shadow-lg p-3 mb-5 bg-white rounded" style="width: 18rem; border-radius: 30px;">
  <div class="card-body" style="background-color: lightgrey;">
    <h3 class="card-title">{{person.name}}</h3>
    <p class="card-text">Number: {{person.contact_entry}}</p>
  </div>
</div>
</div>

       {% endfor %}
</div>
 {% endif %}



 {% else %}
 <h2 align="center" style="font-family:OCR A Std, monospace">Welcome! Please Register</h2>
{% endif %}

</div>

{% endblock %}

contacts_app/contacts_app/templates/app/login.html
{% extends 'app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="POST" action="{% url 'app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password">Password:</label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

contacts_app/contacts_app/templates/app/registration.html
{% extends "app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1 align="center" style="margin-bottom:30px;">Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form class="form-horizontal" enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}